/**
 * WorkflowBuilder Constants
 * Shared constants for WorkflowBuilder sub-components
 */

import {
  Clock,
  Mail,
  MessageSquare,
  UserPlus,
  Tag,
  Bell,
  Calendar,
  Gift,
  Users,
  CheckCircle,
  XCircle,
  RefreshCw,
  Zap,
} from 'lucide-react';

export const TRIGGER_TYPES = {
  PATIENT_CREATED: {
    id: 'PATIENT_CREATED',
    label: { en: 'Patient Created', no: 'Ny pasient opprettet' },
    icon: UserPlus,
    color: 'blue',
    description: {
      en: 'Triggered when a new patient is created',
      no: 'Utloses nar en ny pasient opprettes',
    },
  },
  APPOINTMENT_SCHEDULED: {
    id: 'APPOINTMENT_SCHEDULED',
    label: { en: 'Appointment Scheduled', no: 'Time bestilt' },
    icon: Calendar,
    color: 'green',
    description: {
      en: 'Triggered when an appointment is booked',
      no: 'Utloses nar en time bestilles',
    },
  },
  APPOINTMENT_COMPLETED: {
    id: 'APPOINTMENT_COMPLETED',
    label: { en: 'Appointment Completed', no: 'Time fullfort' },
    icon: CheckCircle,
    color: 'emerald',
    description: {
      en: 'Triggered when an appointment is completed',
      no: 'Utloses nar en time er fullfort',
    },
  },
  APPOINTMENT_MISSED: {
    id: 'APPOINTMENT_MISSED',
    label: { en: 'Appointment Missed', no: 'Uteblitt fra time' },
    icon: XCircle,
    color: 'red',
    description: {
      en: 'Triggered when patient misses appointment',
      no: 'Utloses nar pasient uteblir',
    },
  },
  DAYS_SINCE_VISIT: {
    id: 'DAYS_SINCE_VISIT',
    label: { en: 'Days Since Last Visit', no: 'Dager siden siste besok' },
    icon: Clock,
    color: 'orange',
    description: {
      en: 'Triggered after X days without visit',
      no: 'Utloses etter X dager uten besok',
    },
  },
  BIRTHDAY: {
    id: 'BIRTHDAY',
    label: { en: 'Patient Birthday', no: 'Pasientens bursdag' },
    icon: Gift,
    color: 'purple',
    description: { en: 'Triggered on patient birthday', no: 'Utloses pa pasientens bursdag' },
  },
  LIFECYCLE_CHANGE: {
    id: 'LIFECYCLE_CHANGE',
    label: { en: 'Lifecycle Stage Changed', no: 'Livssyklusstatus endret' },
    icon: RefreshCw,
    color: 'indigo',
    description: {
      en: 'Triggered when lifecycle stage changes',
      no: 'Utloses nar livssyklusstatus endres',
    },
  },
  CUSTOM: {
    id: 'CUSTOM',
    label: { en: 'Custom Trigger', no: 'Egendefinert trigger' },
    icon: Zap,
    color: 'gray',
    description: { en: 'Custom event trigger', no: 'Egendefinert hendelsestrigger' },
  },
};

export const ACTION_TYPES = {
  SEND_SMS: {
    id: 'SEND_SMS',
    label: { en: 'Send SMS', no: 'Send SMS' },
    icon: MessageSquare,
    color: 'green',
  },
  SEND_EMAIL: {
    id: 'SEND_EMAIL',
    label: { en: 'Send Email', no: 'Send e-post' },
    icon: Mail,
    color: 'blue',
  },
  CREATE_FOLLOW_UP: {
    id: 'CREATE_FOLLOW_UP',
    label: { en: 'Create Follow-up', no: 'Opprett oppfolging' },
    icon: Calendar,
    color: 'orange',
  },
  UPDATE_STATUS: {
    id: 'UPDATE_STATUS',
    label: { en: 'Update Status', no: 'Oppdater status' },
    icon: RefreshCw,
    color: 'purple',
  },
  UPDATE_LIFECYCLE: {
    id: 'UPDATE_LIFECYCLE',
    label: { en: 'Update Lifecycle', no: 'Oppdater livssyklus' },
    icon: Users,
    color: 'indigo',
  },
  NOTIFY_STAFF: {
    id: 'NOTIFY_STAFF',
    label: { en: 'Notify Staff', no: 'Varsle ansatte' },
    icon: Bell,
    color: 'yellow',
  },
  ADD_TAG: {
    id: 'ADD_TAG',
    label: { en: 'Add Tag', no: 'Legg til etikett' },
    icon: Tag,
    color: 'pink',
  },
};

export const CONDITION_FIELDS = [
  {
    id: 'status',
    label: { en: 'Patient Status', no: 'Pasientstatus' },
    type: 'select',
    options: ['ACTIVE', 'INACTIVE', 'FINISHED'],
  },
  {
    id: 'lifecycle_stage',
    label: { en: 'Lifecycle Stage', no: 'Livssyklusstatus' },
    type: 'select',
    options: ['NEW', 'ONBOARDING', 'ACTIVE', 'AT_RISK', 'INACTIVE', 'LOST', 'REACTIVATED'],
  },
  { id: 'total_visits', label: { en: 'Total Visits', no: 'Totalt besok' }, type: 'number' },
  { id: 'consent_sms', label: { en: 'SMS Consent', no: 'SMS-samtykke' }, type: 'boolean' },
  { id: 'consent_email', label: { en: 'Email Consent', no: 'E-post-samtykke' }, type: 'boolean' },
  { id: 'is_vip', label: { en: 'VIP Patient', no: 'VIP-pasient' }, type: 'boolean' },
  {
    id: 'preferred_contact_method',
    label: { en: 'Preferred Contact', no: 'Foretrukket kontakt' },
    type: 'select',
    options: ['SMS', 'EMAIL', 'PHONE'],
  },
];

export const OPERATORS = {
  equals: { label: { en: 'Equals', no: 'Er lik' } },
  not_equals: { label: { en: 'Not Equals', no: 'Er ikke lik' } },
  greater_than: { label: { en: 'Greater Than', no: 'Storre enn' } },
  less_than: { label: { en: 'Less Than', no: 'Mindre enn' } },
  contains: { label: { en: 'Contains', no: 'Inneholder' } },
  is_empty: { label: { en: 'Is Empty', no: 'Er tom' } },
  is_not_empty: { label: { en: 'Is Not Empty', no: 'Er ikke tom' } },
};

export const LABELS = {
  en: {
    title: 'Create Workflow',
    titleEdit: 'Edit Workflow',
    name: 'Workflow Name',
    namePlaceholder: 'e.g., Welcome New Patients',
    description: 'Description',
    descriptionPlaceholder: 'Describe what this workflow does...',
    trigger: 'Trigger',
    triggerSection: 'When should this workflow run?',
    selectTrigger: 'Select a trigger',
    conditions: 'Conditions',
    conditionsSection: 'Filter which patients this applies to',
    addCondition: 'Add Condition',
    actions: 'Actions',
    actionsSection: 'What should happen?',
    addAction: 'Add Action',
    settings: 'Settings',
    maxRuns: 'Max runs per patient',
    maxRunsHelp: '0 = unlimited',
    enabled: 'Enabled',
    save: 'Save Workflow',
    cancel: 'Cancel',
    test: 'Test Workflow',
    preview: 'Preview',
    selectPatient: 'Select test patient',
    runTest: 'Run Test',
    testResults: 'Test Results',
    conditionsPassed: 'Conditions Passed',
    conditionsFailed: 'Conditions Failed',
    actionsPreview: 'Actions that would execute',
    noActions: 'No actions configured',
    delayHours: 'Delay (hours)',
    message: 'Message',
    subject: 'Subject',
    body: 'Body',
    priority: 'Priority',
    dueInDays: 'Due in (days)',
    assignTo: 'Assign to',
    notifyRoles: 'Notify roles',
    tag: 'Tag',
    newValue: 'New value',
    field: 'Field',
    operator: 'Operator',
    value: 'Value',
    and: 'AND',
    or: 'OR',
    days: 'Days',
    daysBefore: 'Days before',
    appointmentType: 'Appointment type',
    fromStage: 'From stage',
    toStage: 'To stage',
    variables: 'Available variables: {firstName}, {lastName}, {phone}, {email}',
    required: 'Required',
    errorName: 'Workflow name is required',
    errorTrigger: 'Please select a trigger type',
    errorActions: 'Add at least one action',
  },
  no: {
    title: 'Opprett arbeidsflyt',
    titleEdit: 'Rediger arbeidsflyt',
    name: 'Navn pa arbeidsflyt',
    namePlaceholder: 'f.eks. Velkommen nye pasienter',
    description: 'Beskrivelse',
    descriptionPlaceholder: 'Beskriv hva denne arbeidsflyten gjor...',
    trigger: 'Trigger',
    triggerSection: 'Nar skal denne arbeidsflyten kjore?',
    selectTrigger: 'Velg en trigger',
    conditions: 'Betingelser',
    conditionsSection: 'Filtrer hvilke pasienter dette gjelder',
    addCondition: 'Legg til betingelse',
    actions: 'Handlinger',
    actionsSection: 'Hva skal skje?',
    addAction: 'Legg til handling',
    settings: 'Innstillinger',
    maxRuns: 'Maks kjoringer per pasient',
    maxRunsHelp: '0 = ubegrenset',
    enabled: 'Aktivert',
    save: 'Lagre arbeidsflyt',
    cancel: 'Avbryt',
    test: 'Test arbeidsflyt',
    preview: 'Forhandsvisning',
    selectPatient: 'Velg testpasient',
    runTest: 'Kjor test',
    testResults: 'Testresultater',
    conditionsPassed: 'Betingelser oppfylt',
    conditionsFailed: 'Betingelser ikke oppfylt',
    actionsPreview: 'Handlinger som ville utfores',
    noActions: 'Ingen handlinger konfigurert',
    delayHours: 'Forsinkelse (timer)',
    message: 'Melding',
    subject: 'Emne',
    body: 'Innhold',
    priority: 'Prioritet',
    dueInDays: 'Forfall om (dager)',
    assignTo: 'Tildel til',
    notifyRoles: 'Varsle roller',
    tag: 'Etikett',
    newValue: 'Ny verdi',
    field: 'Felt',
    operator: 'Operator',
    value: 'Verdi',
    and: 'OG',
    or: 'ELLER',
    days: 'Dager',
    daysBefore: 'Dager for',
    appointmentType: 'Timetype',
    fromStage: 'Fra status',
    toStage: 'Til status',
    variables: 'Tilgjengelige variabler: {firstName}, {lastName}, {phone}, {email}',
    required: 'Pakrevd',
    errorName: 'Arbeidsflytens navn er pakrevd',
    errorTrigger: 'Velg en triggertype',
    errorActions: 'Legg til minst en handling',
  },
};
