/**
 * CSVColumnMapper constants - field definitions and standard mappings
 */

// Patient field definitions with Norwegian labels
export const PATIENT_FIELDS = [
  { field: 'first_name', label: 'First Name', labelNo: 'Fornavn', required: true, group: 'basic' },
  { field: 'last_name', label: 'Last Name', labelNo: 'Etternavn', required: true, group: 'basic' },
  { field: 'email', label: 'Email', labelNo: 'E-post', required: false, group: 'contact' },
  { field: 'phone', label: 'Mobile Phone', labelNo: 'Mobil', required: false, group: 'contact' },
  {
    field: 'home_phone',
    label: 'Home Phone',
    labelNo: 'Hjemmetelefon',
    required: false,
    group: 'contact',
  },
  {
    field: 'work_phone',
    label: 'Work Phone',
    labelNo: 'Arbeidstelefon',
    required: false,
    group: 'contact',
  },
  {
    field: 'address_street',
    label: 'Street Address',
    labelNo: 'Gateadresse',
    required: false,
    group: 'address',
  },
  { field: 'address_city', label: 'City', labelNo: 'Poststed', required: false, group: 'address' },
  {
    field: 'address_postal_code',
    label: 'Postal Code',
    labelNo: 'Postnummer',
    required: false,
    group: 'address',
  },
  { field: 'country', label: 'Country', labelNo: 'Land', required: false, group: 'address' },
  {
    field: 'date_of_birth',
    label: 'Date of Birth',
    labelNo: 'Fodselsdato',
    required: false,
    group: 'personal',
  },
  { field: 'gender', label: 'Gender', labelNo: 'Kjonn', required: false, group: 'personal' },
  {
    field: 'personal_number',
    label: 'National ID',
    labelNo: 'Fodselsnummer',
    required: false,
    group: 'personal',
  },
  { field: 'notes', label: 'Notes', labelNo: 'Notater', required: false, group: 'other' },
  {
    field: 'solvit_id',
    label: 'External ID',
    labelNo: 'Ekstern ID',
    required: false,
    group: 'other',
  },
  { field: 'category', label: 'Category', labelNo: 'Kategori', required: false, group: 'other' },
  { field: 'status', label: 'Status', labelNo: 'Status', required: false, group: 'other' },
  {
    field: 'referral_source',
    label: 'Referral Source',
    labelNo: 'Henvist av',
    required: false,
    group: 'other',
  },
];

// Standard column name mappings for auto-detection
export const STANDARD_MAPPINGS = {
  first_name: 'first_name',
  firstname: 'first_name',
  'first name': 'first_name',
  fornavn: 'first_name',
  'given name': 'first_name',
  givenname: 'first_name',
  last_name: 'last_name',
  lastname: 'last_name',
  'last name': 'last_name',
  etternavn: 'last_name',
  'family name': 'last_name',
  familyname: 'last_name',
  surname: 'last_name',
  email: 'email',
  'e-mail': 'email',
  epost: 'email',
  'e-post': 'email',
  'email address': 'email',
  phone: 'phone',
  telefon: 'phone',
  mobile: 'phone',
  mobil: 'phone',
  cell: 'phone',
  mobiltelefon: 'phone',
  'phone number': 'phone',
  phonenumber: 'phone',
  telefonnummer: 'phone',
  home_phone: 'home_phone',
  'home phone': 'home_phone',
  hjemmetelefon: 'home_phone',
  work_phone: 'work_phone',
  'work phone': 'work_phone',
  arbeidstelefon: 'work_phone',
  'jobb telefon': 'work_phone',
  address: 'address_street',
  street: 'address_street',
  'street address': 'address_street',
  adresse: 'address_street',
  gateadresse: 'address_street',
  city: 'address_city',
  by: 'address_city',
  sted: 'address_city',
  poststed: 'address_city',
  postal_code: 'address_postal_code',
  postalcode: 'address_postal_code',
  zip: 'address_postal_code',
  zipcode: 'address_postal_code',
  postnummer: 'address_postal_code',
  'post code': 'address_postal_code',
  country: 'country',
  land: 'country',
  date_of_birth: 'date_of_birth',
  dateofbirth: 'date_of_birth',
  dob: 'date_of_birth',
  birthday: 'date_of_birth',
  birthdate: 'date_of_birth',
  'birth date': 'date_of_birth',
  fodselsdato: 'date_of_birth',
  gender: 'gender',
  sex: 'gender',
  kjonn: 'gender',
  national_id: 'personal_number',
  nationalid: 'personal_number',
  personal_number: 'personal_number',
  personnummer: 'personal_number',
  fodselsnummer: 'personal_number',
  fnr: 'personal_number',
  ssn: 'personal_number',
  notes: 'notes',
  notat: 'notes',
  notater: 'notes',
  comments: 'notes',
  kommentar: 'notes',
  solvit_id: 'solvit_id',
  solvitid: 'solvit_id',
  external_id: 'solvit_id',
  externalid: 'solvit_id',
  'pasient id': 'solvit_id',
  category: 'category',
  kategori: 'category',
  status: 'status',
  'pasient status': 'status',
  referral_source: 'referral_source',
  referred_by: 'referral_source',
  henvist_av: 'referral_source',
  henvisningskilde: 'referral_source',
};

// Group definitions for better organization
export const FIELD_GROUPS = {
  basic: { label: 'Basic Info', labelNo: 'Grunnleggende' },
  contact: { label: 'Contact', labelNo: 'Kontakt' },
  address: { label: 'Address', labelNo: 'Adresse' },
  personal: { label: 'Personal', labelNo: 'Personlig' },
  other: { label: 'Other', labelNo: 'Annet' },
};

// Norwegian translations
export const TRANSLATIONS = {
  en: {
    title: 'CSV Column Mapper',
    subtitle: 'Map CSV columns to patient fields',
    uploadFile: 'Upload CSV File',
    dropHere: 'Drop CSV file here or click to browse',
    supportedFormats: 'Supports .csv files with comma, semicolon, or tab separators',
    preview: 'Data Preview',
    showing: 'Showing',
    of: 'of',
    rows: 'rows',
    columnMappings: 'Column Mappings',
    csvColumn: 'CSV Column',
    patientField: 'Patient Field',
    autoDetected: 'Auto-detected',
    notMapped: 'Not Mapped',
    selectField: 'Select field...',
    requiredFields: 'Required Fields',
    missingRequired: 'The following required fields are not mapped:',
    allRequiredMapped: 'All required fields are mapped',
    validation: 'Validation',
    validationWarnings: 'Validation Warnings',
    noWarnings: 'No validation warnings',
    saveTemplate: 'Save Mapping Template',
    loadTemplate: 'Load Template',
    templateName: 'Template Name',
    savedTemplates: 'Saved Templates',
    noTemplates: 'No saved templates',
    save: 'Save',
    load: 'Load',
    delete: 'Delete',
    cancel: 'Cancel',
    apply: 'Apply Mapping',
    reset: 'Reset',
    autoDetect: 'Auto-Detect',
    clearMappings: 'Clear All',
    mappedFields: 'Mapped Fields',
    unmappedColumns: 'Unmapped Columns',
    previewMapped: 'Preview Mapped Data',
    parsedRows: 'Parsed Rows',
    errors: 'Errors',
    warnings: 'Warnings',
    sampleData: 'Sample Data',
    noFile: 'No file selected',
    invalidFile: 'Invalid file format',
    parseError: 'Error parsing CSV file',
    dragDrop: 'Drag and drop to reorder',
    group: 'Group',
    required: 'Required',
    optional: 'Optional',
    close: 'Close',
  },
  no: {
    title: 'CSV Kolonnekartlegger',
    subtitle: 'Koble CSV-kolonner til pasientfelt',
    uploadFile: 'Last opp CSV-fil',
    dropHere: 'Slipp CSV-fil her eller klikk for a bla',
    supportedFormats: 'Stotter .csv-filer med komma, semikolon eller tab-separatorer',
    preview: 'Forhandsvisning',
    showing: 'Viser',
    of: 'av',
    rows: 'rader',
    columnMappings: 'Kolonnekoblinger',
    csvColumn: 'CSV-kolonne',
    patientField: 'Pasientfelt',
    autoDetected: 'Automatisk oppdaget',
    notMapped: 'Ikke koblet',
    selectField: 'Velg felt...',
    requiredFields: 'Pakrevde felt',
    missingRequired: 'Folgende pakrevde felt er ikke koblet:',
    allRequiredMapped: 'Alle pakrevde felt er koblet',
    validation: 'Validering',
    validationWarnings: 'Valideringsadvarsler',
    noWarnings: 'Ingen valideringsadvarsler',
    saveTemplate: 'Lagre Mal',
    loadTemplate: 'Last Mal',
    templateName: 'Malnavn',
    savedTemplates: 'Lagrede Maler',
    noTemplates: 'Ingen lagrede maler',
    save: 'Lagre',
    load: 'Last',
    delete: 'Slett',
    cancel: 'Avbryt',
    apply: 'Bruk Kobling',
    reset: 'Tilbakestill',
    autoDetect: 'Auto-Oppdag',
    clearMappings: 'Fjern Alle',
    mappedFields: 'Koblede Felt',
    unmappedColumns: 'Ukoblede Kolonner',
    previewMapped: 'Forhandsvis Kartlagt Data',
    parsedRows: 'Behandlede Rader',
    errors: 'Feil',
    warnings: 'Advarsler',
    sampleData: 'Eksempeldata',
    noFile: 'Ingen fil valgt',
    invalidFile: 'Ugyldig filformat',
    parseError: 'Feil ved behandling av CSV-fil',
    dragDrop: 'Dra og slipp for a omorganisere',
    group: 'Gruppe',
    required: 'Pakrevet',
    optional: 'Valgfritt',
    close: 'Lukk',
  },
};
