/**
 * CranialNervePanel Data - Cranial nerve definitions and finding states
 *
 * Contains all 12 cranial nerves with their OSCE-style test items,
 * bilingual labels, and clinical red flags.
 */

import { Eye, Ear, Wind, Smile, MessageCircle } from 'lucide-react';

// Finding states
export const FINDING_STATES = {
  NOT_TESTED: {
    value: 'NT',
    label: 'NT',
    labelNo: 'IT',
    color: 'bg-gray-100 text-gray-500 dark:text-gray-400',
  },
  NORMAL: {
    value: 'normal',
    label: 'Normal',
    labelNo: 'Normal',
    color: 'bg-green-100 text-green-700',
  },
  ABNORMAL: {
    value: 'abnormal',
    label: 'Abnormal',
    labelNo: 'Patologisk',
    color: 'bg-red-100 text-red-700',
  },
  EQUIVOCAL: {
    value: 'equivocal',
    label: 'Equivocal',
    labelNo: 'Usikker',
    color: 'bg-amber-100 text-amber-700',
  },
};

// Complete Cranial Nerve data with all 12 nerves
export const CRANIAL_NERVES = [
  {
    id: 'cn1',
    number: 'I',
    name: 'Olfactory',
    nameNo: 'Olfaktorius',
    function: 'Smell',
    functionNo: 'Lukt',
    icon: Wind,
    bilateral: true,
    tests: [
      {
        id: 'smell_identification',
        name: 'Smell Identification',
        nameNo: 'Luktidentifikasjon',
        description:
          'Test each nostril separately with familiar scents (coffee, vanilla, peppermint)',
        descriptionNo: 'Test hvert nesebor separat med kjente lukter (kaffe, vanilje, peppermynte)',
        findings: ['normal', 'anosmia', 'hyposmia', 'parosmia'],
      },
    ],
    redFlags: ['Anosmia after head trauma', 'Unilateral loss (tumor)'],
    redFlagsNo: ['Anosmi etter hodeskade', 'Unilateral tap (tumor)'],
  },
  {
    id: 'cn2',
    number: 'II',
    name: 'Optic',
    nameNo: 'Optikus',
    function: 'Vision',
    functionNo: 'Syn',
    icon: Eye,
    bilateral: true,
    tests: [
      {
        id: 'visual_acuity',
        name: 'Visual Acuity',
        nameNo: 'Visus',
        description: 'Snellen chart or finger counting',
        descriptionNo: 'Snellen-tavle eller fingertelling',
      },
      {
        id: 'visual_fields',
        name: 'Visual Fields',
        nameNo: 'Synsfelt',
        description: 'Confrontation testing in all quadrants',
        descriptionNo: 'Konfrontasjonstest i alle kvadranter',
      },
      {
        id: 'pupil_direct',
        name: 'Pupil Direct Response',
        nameNo: 'Direkte pupillrefleks',
        description: 'Shine light in eye, observe ipsilateral constriction',
        descriptionNo: 'Lys i øyet, observer ipsilateral konstriksjon',
      },
      {
        id: 'pupil_consensual',
        name: 'Pupil Consensual Response',
        nameNo: 'Konsensuel pupillrefleks',
        description: 'Shine light in one eye, observe contralateral constriction',
        descriptionNo: 'Lys i ett øye, observer kontralateral konstriksjon',
      },
      {
        id: 'rapd',
        name: 'RAPD (Swinging Flashlight)',
        nameNo: 'RAPD (Svingende lommelykt)',
        description: 'Relative afferent pupillary defect test',
        descriptionNo: 'Relativ afferent pupilldefekt-test',
      },
      {
        id: 'fundoscopy',
        name: 'Fundoscopy',
        nameNo: 'Fundoskopi',
        description: 'Examine optic disc and retina',
        descriptionNo: 'Undersøk papillen og retina',
      },
    ],
    redFlags: ['Papilledema', 'Optic atrophy', 'RAPD positive'],
    redFlagsNo: ['Papilleødem', 'Optikusatrofi', 'RAPD positiv'],
  },
  {
    id: 'cn3',
    number: 'III',
    name: 'Oculomotor',
    nameNo: 'Okulomotorius',
    function: 'Eye movement, pupil, eyelid',
    functionNo: 'Øyebevegelse, pupill, øyelokk',
    icon: Eye,
    bilateral: true,
    tests: [
      {
        id: 'eyelid_ptosis',
        name: 'Eyelid Position (Ptosis)',
        nameNo: 'Øyelokksposisjon (Ptose)',
        description: 'Observe for drooping eyelid',
        descriptionNo: 'Observer hengende øyelokk',
      },
      {
        id: 'pupil_size',
        name: 'Pupil Size',
        nameNo: 'Pupillstørrelse',
        description: 'Compare pupil size bilaterally',
        descriptionNo: 'Sammenlign pupillstørrelse bilateralt',
      },
      {
        id: 'eye_movement_up',
        name: 'Eye Movement - Up',
        nameNo: 'Øyebevegelse - Opp',
        description: 'Superior rectus and inferior oblique',
        descriptionNo: 'Superior rektus og inferior oblikus',
      },
      {
        id: 'eye_movement_down',
        name: 'Eye Movement - Down',
        nameNo: 'Øyebevegelse - Ned',
        description: 'Inferior rectus',
        descriptionNo: 'Inferior rektus',
      },
      {
        id: 'eye_movement_medial',
        name: 'Eye Movement - Medial',
        nameNo: 'Øyebevegelse - Medialt',
        description: 'Medial rectus (adduction)',
        descriptionNo: 'Medial rektus (adduksjon)',
      },
      {
        id: 'accommodation',
        name: 'Accommodation',
        nameNo: 'Akkommodasjon',
        description: 'Near response - pupil constriction and convergence',
        descriptionNo: 'Nærrespons - pupillkonstriksjon og konvergens',
      },
    ],
    redFlags: [
      'Complete CN III palsy with pupil involvement (aneurysm)',
      'Painful ophthalmoplegia',
    ],
    redFlagsNo: [
      'Komplett CN III parese med pupillaffeksjon (aneurisme)',
      'Smertefull oftalmoplegi',
    ],
  },
  {
    id: 'cn4',
    number: 'IV',
    name: 'Trochlear',
    nameNo: 'Trochlearis',
    function: 'Eye movement (down and in)',
    functionNo: 'Øyebevegelse (ned og inn)',
    icon: Eye,
    bilateral: true,
    tests: [
      {
        id: 'eye_down_in',
        name: 'Eye Movement - Down and In',
        nameNo: 'Øyebevegelse - Ned og inn',
        description: 'Superior oblique - look down and medially',
        descriptionNo: 'Superior oblikus - se ned og medialt',
      },
      {
        id: 'head_tilt',
        name: 'Head Tilt Test',
        nameNo: 'Hodehelningstest',
        description: 'Bielschowsky head tilt test for SO palsy',
        descriptionNo: 'Bielschowsky hodehelningstest for SO parese',
      },
    ],
    redFlags: ['Vertical diplopia worse looking down (reading, stairs)'],
    redFlagsNo: ['Vertikal diplopi verre ved å se ned (lesing, trapper)'],
  },
  {
    id: 'cn5',
    number: 'V',
    name: 'Trigeminal',
    nameNo: 'Trigeminus',
    function: 'Face sensation, mastication',
    functionNo: 'Ansiktssensibilitet, tygging',
    icon: Smile,
    bilateral: true,
    tests: [
      {
        id: 'sensation_v1',
        name: 'Sensation V1 (Ophthalmic)',
        nameNo: 'Sensibilitet V1 (Oftalmisk)',
        description: 'Light touch forehead, upper eyelid',
        descriptionNo: 'Lett berøring panne, øvre øyelokk',
      },
      {
        id: 'sensation_v2',
        name: 'Sensation V2 (Maxillary)',
        nameNo: 'Sensibilitet V2 (Maksillær)',
        description: 'Light touch cheek, upper lip, lateral nose',
        descriptionNo: 'Lett berøring kinn, overleppe, lateral nese',
      },
      {
        id: 'sensation_v3',
        name: 'Sensation V3 (Mandibular)',
        nameNo: 'Sensibilitet V3 (Mandibulær)',
        description: 'Light touch jaw, lower lip, chin',
        descriptionNo: 'Lett berøring kjeve, underleppe, hake',
      },
      {
        id: 'corneal_reflex',
        name: 'Corneal Reflex',
        nameNo: 'Kornealrefleks',
        description: 'Touch cornea with cotton wisp - blink response',
        descriptionNo: 'Berør kornea med bomullsdott - blunkerespons',
      },
      {
        id: 'jaw_clench',
        name: 'Jaw Clench (Masseter)',
        nameNo: 'Kjevesammenbitn (Masseter)',
        description: 'Palpate masseter during clenching',
        descriptionNo: 'Palper masseter under sammenbiting',
      },
      {
        id: 'jaw_jerk',
        name: 'Jaw Jerk Reflex',
        nameNo: 'Kjeverefleks',
        description: 'Tap chin with mouth slightly open',
        descriptionNo: 'Bank på haken med munnen litt åpen',
      },
      {
        id: 'jaw_deviation',
        name: 'Jaw Opening Deviation',
        nameNo: 'Kjeveåpningsdeviasjon',
        description: 'Observe jaw deviation on opening (pterygoids)',
        descriptionNo: 'Observer kjevedeviasjon ved åpning (pterygoideus)',
      },
    ],
    redFlags: ['Trigeminal neuralgia', 'Numbness with CN V, VI, VII (cavernous sinus)'],
    redFlagsNo: ['Trigeminusnevralgi', 'Nummenhet med CN V, VI, VII (sinus cavernosus)'],
  },
  {
    id: 'cn6',
    number: 'VI',
    name: 'Abducens',
    nameNo: 'Abducens',
    function: 'Eye movement (lateral)',
    functionNo: 'Øyebevegelse (lateralt)',
    icon: Eye,
    bilateral: true,
    tests: [
      {
        id: 'eye_abduction',
        name: 'Eye Abduction',
        nameNo: 'Øyeabduksjon',
        description: 'Lateral rectus - look laterally',
        descriptionNo: 'Lateral rektus - se lateralt',
      },
      {
        id: 'horizontal_diplopia',
        name: 'Horizontal Diplopia Assessment',
        nameNo: 'Horisontal diplopivurdering',
        description: 'Worse at distance, looking toward affected side',
        descriptionNo: 'Verre på avstand, ser mot affisert side',
      },
    ],
    redFlags: ['Isolated CN VI palsy in elderly (microvascular)', 'With papilledema (raised ICP)'],
    redFlagsNo: ['Isolert CN VI parese hos eldre (mikrovaskulær)', 'Med papilleødem (økt ICP)'],
  },
  {
    id: 'cn7',
    number: 'VII',
    name: 'Facial',
    nameNo: 'Facialis',
    function: 'Face movement, taste (anterior 2/3)',
    functionNo: 'Ansiktsbevegelse, smak (fremre 2/3)',
    icon: Smile,
    bilateral: true,
    tests: [
      {
        id: 'raise_eyebrows',
        name: 'Raise Eyebrows',
        nameNo: 'Løft øyenbryn',
        description: 'Frontalis muscle - forehead wrinkling',
        descriptionNo: 'Frontalismuskel - pannerynking',
      },
      {
        id: 'close_eyes_tight',
        name: 'Close Eyes Tightly',
        nameNo: 'Lukk øynene stramt',
        description: 'Orbicularis oculi - resist opening',
        descriptionNo: 'Orbicularis oculi - motstå åpning',
      },
      {
        id: 'puff_cheeks',
        name: 'Puff Out Cheeks',
        nameNo: 'Blås ut kinnene',
        description: 'Buccinator - check for air leak',
        descriptionNo: 'Buccinator - sjekk for luftlekkasje',
      },
      {
        id: 'show_teeth',
        name: 'Show Teeth / Smile',
        nameNo: 'Vis tenner / Smil',
        description: 'Observe symmetry of nasolabial folds',
        descriptionNo: 'Observer symmetri av nasolabialfolder',
      },
      {
        id: 'taste_anterior',
        name: 'Taste (Anterior 2/3 Tongue)',
        nameNo: 'Smak (Fremre 2/3 tunge)',
        description: 'Test with sugar, salt, citric acid',
        descriptionNo: 'Test med sukker, salt, sitronsyre',
      },
    ],
    redFlags: ['Upper vs Lower motor neuron pattern', 'Bells palsy - exclude Lyme, Ramsay Hunt'],
    redFlagsNo: [
      'Øvre vs nedre motornevron mønster',
      'Bells parese - utelukk Borrelia, Ramsay Hunt',
    ],
  },
  {
    id: 'cn8',
    number: 'VIII',
    name: 'Vestibulocochlear',
    nameNo: 'Vestibulocochlearis',
    function: 'Hearing, balance',
    functionNo: 'Hørsel, balanse',
    icon: Ear,
    bilateral: true,
    tests: [
      {
        id: 'whisper_test',
        name: 'Whisper Test',
        nameNo: 'Hvisketest',
        description: 'Whisper numbers/letters at 60cm, occlude opposite ear',
        descriptionNo: 'Hvisk tall/bokstaver på 60cm, okkluder motsatt øre',
      },
      {
        id: 'finger_rub',
        name: 'Finger Rub Test',
        nameNo: 'Fingergnidningstest',
        description: 'Rub fingers near each ear',
        descriptionNo: 'Gni fingre nær hvert øre',
      },
      {
        id: 'rinne_test',
        name: 'Rinne Test',
        nameNo: 'Rinnes prøve',
        description: '512Hz tuning fork: air vs bone conduction',
        descriptionNo: '512Hz stemmegaffel: luft vs beinledning',
      },
      {
        id: 'weber_test',
        name: 'Weber Test',
        nameNo: 'Webers prøve',
        description: '512Hz tuning fork on vertex - lateralization',
        descriptionNo: '512Hz stemmegaffel på vertex - lateralisering',
      },
      {
        id: 'nystagmus',
        name: 'Nystagmus Assessment',
        nameNo: 'Nystagmusvurdering',
        description: 'Observe for spontaneous or gaze-evoked nystagmus',
        descriptionNo: 'Observer for spontan eller blikkutløst nystagmus',
      },
      {
        id: 'head_impulse',
        name: 'Head Impulse Test (HIT)',
        nameNo: 'Hodeimpulstest (HIT)',
        description: 'Rapid head turn while fixating on nose',
        descriptionNo: 'Rask hodedreining mens pasienten fikserer på nesen',
      },
      {
        id: 'dix_hallpike',
        name: 'Dix-Hallpike Test',
        nameNo: 'Dix-Hallpike test',
        description: 'BPPV assessment - posterior canal',
        descriptionNo: 'BPPV-vurdering - bakre buegang',
      },
    ],
    redFlags: ['Sudden unilateral hearing loss (emergency)', 'Vertigo with neurological signs'],
    redFlagsNo: ['Plutselig unilateralt hørselstap (ø-hjelp)', 'Svimmelhet med nevrologiske tegn'],
  },
  {
    id: 'cn9',
    number: 'IX',
    name: 'Glossopharyngeal',
    nameNo: 'Glossopharyngeus',
    function: 'Taste (posterior 1/3), gag reflex afferent',
    functionNo: 'Smak (bakre 1/3), brekningsrefleks afferent',
    icon: MessageCircle,
    bilateral: true,
    tests: [
      {
        id: 'gag_reflex_afferent',
        name: 'Gag Reflex (Afferent)',
        nameNo: 'Brekningsrefleks (Afferent)',
        description: 'Touch posterior pharynx with tongue depressor - sensation',
        descriptionNo: 'Berør bakre svelg med tungespattel - sensibilitet',
      },
      {
        id: 'taste_posterior',
        name: 'Taste (Posterior 1/3 Tongue)',
        nameNo: 'Smak (Bakre 1/3 tunge)',
        description: 'Test bitter taste on posterior tongue',
        descriptionNo: 'Test bitter smak på bakre tunge',
      },
      {
        id: 'palatal_sensation',
        name: 'Palatal Sensation',
        nameNo: 'Palatal sensibilitet',
        description: 'Light touch to soft palate',
        descriptionNo: 'Lett berøring av bløte gane',
      },
    ],
    redFlags: ['Glossopharyngeal neuralgia', 'Absent gag with swallowing difficulty'],
    redFlagsNo: ['Glossopharyngeusnevralgi', 'Fraværende brekningsrefleks med svelgevansker'],
  },
  {
    id: 'cn10',
    number: 'X',
    name: 'Vagus',
    nameNo: 'Vagus',
    function: 'Palate movement, voice, gag reflex efferent',
    functionNo: 'Ganebevegelse, stemme, brekningsrefleks efferent',
    icon: MessageCircle,
    bilateral: true,
    tests: [
      {
        id: 'voice_quality',
        name: 'Voice Quality',
        nameNo: 'Stemmekvalitet',
        description: 'Listen for hoarseness, nasal speech, bovine cough',
        descriptionNo: 'Lytt etter heshet, nasal tale, "ku-hoste"',
      },
      {
        id: 'palate_elevation',
        name: 'Palate Elevation',
        nameNo: 'Ganehevning',
        description: 'Say "Aah" - observe uvula and soft palate',
        descriptionNo: 'Si "Aah" - observer uvula og bløte gane',
      },
      {
        id: 'uvula_deviation',
        name: 'Uvula Deviation',
        nameNo: 'Uvuladeviasjon',
        description: 'Uvula deviates away from lesion side',
        descriptionNo: 'Uvula devierer bort fra lesjonssiden',
      },
      {
        id: 'gag_reflex_efferent',
        name: 'Gag Reflex (Efferent)',
        nameNo: 'Brekningsrefleks (Efferent)',
        description: 'Motor response to gag - palate elevation',
        descriptionNo: 'Motorisk respons på brekningsrefleks - ganehevning',
      },
      {
        id: 'cough_strength',
        name: 'Cough Strength',
        nameNo: 'Hostekraft',
        description: 'Ask patient to cough - assess strength',
        descriptionNo: 'Be pasienten hoste - vurder styrke',
      },
      {
        id: 'swallowing',
        name: 'Swallowing Assessment',
        nameNo: 'Svelgevurdering',
        description: 'Observe swallowing water - any coughing/choking',
        descriptionNo: 'Observer svelging av vann - hoste/kvelning',
      },
    ],
    redFlags: ['Dysphagia with aspiration', 'Vocal cord paralysis'],
    redFlagsNo: ['Dysfagi med aspirasjon', 'Stemmebåndsparese'],
  },
  {
    id: 'cn11',
    number: 'XI',
    name: 'Accessory',
    nameNo: 'Accessorius',
    function: 'SCM, trapezius',
    functionNo: 'SCM, trapezius',
    icon: Smile,
    bilateral: true,
    tests: [
      {
        id: 'scm_strength',
        name: 'SCM Strength',
        nameNo: 'SCM-styrke',
        description: 'Turn head against resistance - palpate SCM',
        descriptionNo: 'Drei hodet mot motstand - palper SCM',
      },
      {
        id: 'trapezius_strength',
        name: 'Trapezius Strength',
        nameNo: 'Trapezius-styrke',
        description: 'Shrug shoulders against resistance',
        descriptionNo: 'Trekk skuldrene mot motstand',
      },
      {
        id: 'trapezius_bulk',
        name: 'Trapezius Bulk/Wasting',
        nameNo: 'Trapezius bulk/atrofi',
        description: 'Inspect for asymmetry or wasting',
        descriptionNo: 'Inspiser for asymmetri eller atrofi',
      },
      {
        id: 'shoulder_drop',
        name: 'Shoulder Drop',
        nameNo: 'Skulderfall',
        description: 'Observe for unilateral shoulder droop',
        descriptionNo: 'Observer for unilateralt skulderfall',
      },
    ],
    redFlags: ['Wasting after neck surgery/dissection', 'Torticollis'],
    redFlagsNo: ['Atrofi etter nakkekirurgi/disseksjon', 'Torticollis'],
  },
  {
    id: 'cn12',
    number: 'XII',
    name: 'Hypoglossal',
    nameNo: 'Hypoglossus',
    function: 'Tongue movement',
    functionNo: 'Tungebevegelse',
    icon: MessageCircle,
    bilateral: false,
    tests: [
      {
        id: 'tongue_inspection',
        name: 'Tongue Inspection at Rest',
        nameNo: 'Tungeinspeksjon i hvile',
        description: 'Look for wasting, fasciculations',
        descriptionNo: 'Se etter atrofi, fascikulasjoner',
      },
      {
        id: 'tongue_protrusion',
        name: 'Tongue Protrusion',
        nameNo: 'Tungeprotrusjon',
        description: 'Stick out tongue - observe for deviation',
        descriptionNo: 'Stikk ut tungen - observer for deviasjon',
      },
      {
        id: 'tongue_strength',
        name: 'Tongue Strength',
        nameNo: 'Tungestyrke',
        description: 'Push tongue against cheek against resistance',
        descriptionNo: 'Dytt tungen mot kinnet mot motstand',
      },
      {
        id: 'tongue_movements',
        name: 'Rapid Tongue Movements',
        nameNo: 'Raske tungebevegelser',
        description: 'Move tongue rapidly side to side',
        descriptionNo: 'Beveg tungen raskt fra side til side',
      },
      {
        id: 'dysarthria',
        name: 'Dysarthria Assessment',
        nameNo: 'Dysartrivurdering',
        description: 'Repeat "la-la-la", "baby hippopotamus"',
        descriptionNo: 'Gjenta "la-la-la", "British constitution"',
      },
    ],
    redFlags: [
      'LMN: wasting, fasciculations, deviation TO lesion',
      'UMN: spastic, slow, deviation AWAY',
    ],
    redFlagsNo: [
      'Nedre motornevron: atrofi, fascikulasjoner, deviasjon MOT lesjon',
      'Øvre motornevron: spastisk, langsom, deviasjon BORT',
    ],
  },
];
