#!/bin/bash
# weekly-sweep.sh — Run via Task Scheduler (Windows) or cron
# Requires: ANTHROPIC_API_KEY set in environment
# Usage: bash scripts/weekly-sweep.sh

REPORT_DIR="./reports/weekly"
DATE=$(date +%Y-%m-%d)
REPORT_FILE="$REPORT_DIR/sweep-$DATE.md"
mkdir -p "$REPORT_DIR"

echo "# Weekly Sweep Report — $DATE" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Pass 1: Security (CRITICAL)
echo "## Pass 1: Security Analysis" >> "$REPORT_FILE"
npm audit --audit-level=moderate --json 2>/dev/null | \
  claude -p "Analyze this npm audit JSON. List only HIGH and CRITICAL vulnerabilities with package name, severity, and whether it affects production dependencies. Be concise." \
  --output-format text >> "$REPORT_FILE" 2>/dev/null
echo "" >> "$REPORT_FILE"

# Pass 2: PHI Leak Scan (CRITICAL)
echo "## Pass 2: PHI Leak Detection" >> "$REPORT_FILE"
claude -p "Scan the entire codebase for PHI leak risks. Check for:
1. Fødselsnummer patterns (11 consecutive digits) in non-test source files
2. console.log or logger calls that reference patient/health variables
3. API error handlers that might expose patient data in responses
4. Patient data in URL query parameters
5. SELECT * on patient-related database tables
Report only confirmed or high-probability findings with file:line references." \
  --allowedTools "Read,Grep,Glob" \
  --output-format text >> "$REPORT_FILE" 2>/dev/null
echo "" >> "$REPORT_FILE"

# Pass 3: Compliance Check (HIGH)
echo "## Pass 3: Normen/GDPR Compliance" >> "$REPORT_FILE"
claude -p "Check compliance with Norwegian healthcare requirements:
1. Are all patient data routes protected with auth middleware?
2. Do all patient data mutations write to audit_log?
3. Are there any http:// (non-TLS) URLs in configuration?
4. Do patient API responses filter fields (no full object returns)?
5. Does consent management flow exist for data collection?
List only violations found, with file:line and specific issue." \
  --allowedTools "Read,Grep,Glob" \
  --output-format text >> "$REPORT_FILE" 2>/dev/null
echo "" >> "$REPORT_FILE"

# Pass 4: Accessibility (HIGH)
echo "## Pass 4: WCAG 2.1 AA Accessibility" >> "$REPORT_FILE"
claude -p "Check accessibility in the frontend React components:
1. Search for img tags without alt attributes
2. Search for form inputs without associated labels
3. Check that HTML element has lang='nb'
4. Look for onClick handlers without keyboard equivalents
Report findings with file:line references." \
  --allowedTools "Read,Grep,Glob" \
  --output-format text >> "$REPORT_FILE" 2>/dev/null
echo "" >> "$REPORT_FILE"

# Pass 5: Test Coverage Gaps (MEDIUM)
echo "## Pass 5: Test Coverage Analysis" >> "$REPORT_FILE"
claude -p "Analyze the test suite for coverage gaps in critical areas:
1. Check which patient data routes have corresponding test files
2. Check which authentication/authorization functions are tested
3. Check which audit logging functions have tests
4. Identify the 5 most critical untested or under-tested files
Focus only on security-critical and compliance-critical gaps." \
  --allowedTools "Read,Grep,Glob" \
  --output-format text >> "$REPORT_FILE" 2>/dev/null
echo "" >> "$REPORT_FILE"

# Pass 6: Code Quality (LOW)
echo "## Pass 6: Code Quality" >> "$REPORT_FILE"
claude -p "Quick code quality scan:
1. Find functions longer than 100 lines that should be split
2. Find duplicated logic that could be extracted
3. Find TODO/FIXME/HACK comments that need attention
4. Check for any TypeScript 'any' types in critical patient data paths
Be very concise — only list items worth acting on this week." \
  --allowedTools "Read,Grep,Glob" \
  --output-format text >> "$REPORT_FILE" 2>/dev/null

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "Generated by weekly-sweep.sh on $DATE" >> "$REPORT_FILE"

echo "Weekly sweep complete. Report: $REPORT_FILE"
